# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FreeBook' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FreeBook

  target 'FreeBookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FreeBookUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod ‘Moya’
pod ‘Kingfisher’
pod ‘SwiftyJSON’
pod ‘SwiftyUserDefaults’
pod ‘Timepiece’
pod ‘Fuzi’

end
